### ISSUE TITLE
Fails if Type::Tiny::XS is installed

### ISSUE THREAD

**Issue by andk** [maxmind/WebService-TeamCity#1]
As per subject. Sample fail report:

http://www.cpantesters.org/cpan/report/c1ef8132-faae-11e5-8461-3b4dee9ed8df

One of my smokers did not have Type::Tiny::XS installed and sent a PASS:

http://www.cpantesters.org/cpan/report/67236430

No idea how awkwardly these things play together, just an observation. Uninstalling Type::Tiny::XS lets the tests for MAXMIND/WebService-TeamCity-0.03.tar.gz pass. At least with today's CPAN. 

HTH&&Thanks,

**Comment by oschwald** [comment]
Thanks. I opened an [issue against `Type::Tiny::XS`](https://github.com/tobyink/p5-type-tiny-xs/issues/5).

**Comment by oschwald** [comment]
This was fixed in `Type::Tiny`.
